name: server tests and release pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  server-tests:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
    permissions:
      actions: write
      contents: write
      packages: write
    with:
      tool: "uv"
      install: "venv --python 3.12 && uv pip install -r requirements-test.txt"
      test: "run pytest"
      build_branch: "run build-dist.py"
      build_main: "run build-dist.py"
      event_name: ${{ github.event_name }}
      root_dir: "server"
      artifact_path: "dist"
      publish_github_release: "true"
      publish_python_libraries: "false"
